import { name as LibName } from '@/../package.json'

const TEMPLATE = `
/* eslint-disable */
// @ts-nocheck

// This file is auto-generated by ${LibName} and should not be edited.
// If changes are needed, restart the dev server to regenerate it.

import '${LibName}'

declare module '${LibName}' {
  interface Register {
    queryKeys: [
{KEYS}
    ]
  }
}
`

export function queryKeysTemplate(keys: string[]) {
  const tab = '\t'
  const keysString = keys
    .filter(Boolean)
    .map((key) => `${tab.repeat(3)}"${key}"`)
    .join(',\n')

  return TEMPLATE.replace('{KEYS}', keysString)
}
