const TEMPLATE = `
import '@frsty/typesafe-query-keys'

// DO NOT EDIT
// This file is auto generated by @frsty/typesafe-query-keys

declare module '@frsty/typesafe-query-keys' {
  interface Register {
    queryKeys: [{KEYS}]
  }
}
`

export function queryKeysTemplate(keys: string[]) {
  const keysString = keys
    .filter(Boolean)
    .map((key) => `"${key}"`)
    .join(', ')

  return TEMPLATE.replace('{KEYS}', keysString)
}
