const TEMPLATE = `
/* eslint-disable */
// @ts-nocheck

// DO NOT EDIT
// This file was auto generated by @frsty/typesafe-query-keys
// This file won't be overwritten, so if you messed it up, rerun the dev server.

import '@frsty/typesafe-query-keys'

declare module '@frsty/typesafe-query-keys' {
  interface Register {
    queryKeys: [
{KEYS}
    ]
  }
}
`

// DO NOT EDIT
// This file is auto generated by @frsty/typesafe-query-keys
// Last updated: ${new Date().toISOString()}

export function queryKeysTemplate(keys: string[]) {
  const tab = '\t'
  const keysString = keys
    .filter(Boolean)
    .map((key) => `${tab.repeat(3)}"${key}"`)
    .join(',\n')

  return TEMPLATE.replace('{KEYS}', keysString)
}
