name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '30 1 * * *'  # Run at 1:30 AM UTC every day
  workflow_dispatch:  # Allow manual triggering

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale due to inactivity. It will be closed if no further activity occurs within 14 days. Thank you for your contributions!'
        stale-pr-message: 'This pull request has been automatically marked as stale due to inactivity. It will be closed if no further activity occurs within 14 days. Thank you for your contributions!'
        close-issue-message: 'This issue has been closed due to inactivity. Feel free to reopen if you still need assistance or want to provide more information.'
        close-pr-message: 'This pull request has been closed due to inactivity. Feel free to reopen if you would like to continue working on it.'
        days-before-stale: 60
        days-before-close: 14
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-labels: 'pinned,security,bug,enhancement,documentation,dependencies'
        exempt-pr-labels: 'pinned,security,bug,enhancement,documentation,dependencies,automerge'
        operations-per-run: 100
        exempt-all-milestones: true
        remove-stale-when-updated: true
        ascending: true
